//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Folder;

export type HomeSite = {
  __typename?: 'HomeSite';
  name?: Maybe<Scalars['String']['output']>;
  fullName?: Maybe<Scalars['String']['output']>;
  contactEmail?: Maybe<Scalars['String']['output']>;
};

export type HomeHero = {
  __typename?: 'HomeHero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  subheading?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaEmail?: Maybe<Scalars['String']['output']>;
};

export type HomeAbout = {
  __typename?: 'HomeAbout';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type HomeStats = {
  __typename?: 'HomeStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type HomeWorkItems = {
  __typename?: 'HomeWorkItems';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HomeWork = {
  __typename?: 'HomeWork';
  heading?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<HomeWorkItems>>>;
};

export type HomeGetInvolved = {
  __typename?: 'HomeGetInvolved';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaEmail?: Maybe<Scalars['String']['output']>;
  note?: Maybe<Scalars['String']['output']>;
};

export type HomeFooter = {
  __typename?: 'HomeFooter';
  tagline?: Maybe<Scalars['String']['output']>;
  contactEmail?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  site?: Maybe<HomeSite>;
  hero?: Maybe<HomeHero>;
  values?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  about?: Maybe<HomeAbout>;
  stats?: Maybe<Array<Maybe<HomeStats>>>;
  work?: Maybe<HomeWork>;
  getInvolved?: Maybe<HomeGetInvolved>;
  footer?: Maybe<HomeFooter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeSiteFilter = {
  name?: InputMaybe<StringFilter>;
  fullName?: InputMaybe<StringFilter>;
  contactEmail?: InputMaybe<StringFilter>;
};

export type HomeHeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  subheading?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaEmail?: InputMaybe<StringFilter>;
};

export type HomeAboutFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HomeStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type HomeWorkItemsFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HomeWorkFilter = {
  heading?: InputMaybe<StringFilter>;
  items?: InputMaybe<HomeWorkItemsFilter>;
};

export type HomeGetInvolvedFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaEmail?: InputMaybe<StringFilter>;
  note?: InputMaybe<StringFilter>;
};

export type HomeFooterFilter = {
  tagline?: InputMaybe<StringFilter>;
  contactEmail?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  site?: InputMaybe<HomeSiteFilter>;
  hero?: InputMaybe<HomeHeroFilter>;
  values?: InputMaybe<StringFilter>;
  about?: InputMaybe<HomeAboutFilter>;
  stats?: InputMaybe<HomeStatsFilter>;
  work?: InputMaybe<HomeWorkFilter>;
  getInvolved?: InputMaybe<HomeGetInvolvedFilter>;
  footer?: InputMaybe<HomeFooterFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
};

export type HomeSiteMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  fullName?: InputMaybe<Scalars['String']['input']>;
  contactEmail?: InputMaybe<Scalars['String']['input']>;
};

export type HomeHeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  subheading?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaEmail?: InputMaybe<Scalars['String']['input']>;
};

export type HomeAboutMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type HomeWorkItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HomeWorkMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<HomeWorkItemsMutation>>>;
};

export type HomeGetInvolvedMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaEmail?: InputMaybe<Scalars['String']['input']>;
  note?: InputMaybe<Scalars['String']['input']>;
};

export type HomeFooterMutation = {
  tagline?: InputMaybe<Scalars['String']['input']>;
  contactEmail?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  site?: InputMaybe<HomeSiteMutation>;
  hero?: InputMaybe<HomeHeroMutation>;
  values?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  about?: InputMaybe<HomeAboutMutation>;
  stats?: InputMaybe<Array<InputMaybe<HomeStatsMutation>>>;
  work?: InputMaybe<HomeWorkMutation>;
  getInvolved?: InputMaybe<HomeGetInvolvedMutation>;
  footer?: InputMaybe<HomeFooterMutation>;
};

export type HomePartsFragment = { __typename: 'Home', values?: Array<string | null> | null, site?: { __typename: 'HomeSite', name?: string | null, fullName?: string | null, contactEmail?: string | null } | null, hero?: { __typename: 'HomeHero', eyebrow?: string | null, heading?: string | null, subheading?: string | null, ctaLabel?: string | null, ctaEmail?: string | null } | null, about?: { __typename: 'HomeAbout', heading?: string | null, body?: Array<string | null> | null } | null, stats?: Array<{ __typename: 'HomeStats', value?: string | null, label?: string | null } | null> | null, work?: { __typename: 'HomeWork', heading?: string | null, items?: Array<{ __typename: 'HomeWorkItems', title?: string | null, body?: string | null } | null> | null } | null, getInvolved?: { __typename: 'HomeGetInvolved', heading?: string | null, body?: string | null, ctaLabel?: string | null, ctaEmail?: string | null, note?: string | null } | null, footer?: { __typename: 'HomeFooter', tagline?: string | null, contactEmail?: string | null } | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, values?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, site?: { __typename: 'HomeSite', name?: string | null, fullName?: string | null, contactEmail?: string | null } | null, hero?: { __typename: 'HomeHero', eyebrow?: string | null, heading?: string | null, subheading?: string | null, ctaLabel?: string | null, ctaEmail?: string | null } | null, about?: { __typename: 'HomeAbout', heading?: string | null, body?: Array<string | null> | null } | null, stats?: Array<{ __typename: 'HomeStats', value?: string | null, label?: string | null } | null> | null, work?: { __typename: 'HomeWork', heading?: string | null, items?: Array<{ __typename: 'HomeWorkItems', title?: string | null, body?: string | null } | null> | null } | null, getInvolved?: { __typename: 'HomeGetInvolved', heading?: string | null, body?: string | null, ctaLabel?: string | null, ctaEmail?: string | null, note?: string | null } | null, footer?: { __typename: 'HomeFooter', tagline?: string | null, contactEmail?: string | null } | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, values?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, site?: { __typename: 'HomeSite', name?: string | null, fullName?: string | null, contactEmail?: string | null } | null, hero?: { __typename: 'HomeHero', eyebrow?: string | null, heading?: string | null, subheading?: string | null, ctaLabel?: string | null, ctaEmail?: string | null } | null, about?: { __typename: 'HomeAbout', heading?: string | null, body?: Array<string | null> | null } | null, stats?: Array<{ __typename: 'HomeStats', value?: string | null, label?: string | null } | null> | null, work?: { __typename: 'HomeWork', heading?: string | null, items?: Array<{ __typename: 'HomeWorkItems', title?: string | null, body?: string | null } | null> | null } | null, getInvolved?: { __typename: 'HomeGetInvolved', heading?: string | null, body?: string | null, ctaLabel?: string | null, ctaEmail?: string | null, note?: string | null } | null, footer?: { __typename: 'HomeFooter', tagline?: string | null, contactEmail?: string | null } | null } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  site {
    __typename
    name
    fullName
    contactEmail
  }
  hero {
    __typename
    eyebrow
    heading
    subheading
    ctaLabel
    ctaEmail
  }
  values
  about {
    __typename
    heading
    body
  }
  stats {
    __typename
    value
    label
  }
  work {
    __typename
    heading
    items {
      __typename
      title
      body
    }
  }
  getInvolved {
    __typename
    heading
    body
    ctaLabel
    ctaEmail
    note
  }
  footer {
    __typename
    tagline
    contactEmail
  }
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  